major rewrite of this tool: * added simple connection script; * Made commands executable; * separated script into functions that can be controlled via a command line argument

diff --git a/startattachable b/startattachable
--- a/startattachable
+++ b/startattachable
@@ -1,30 +1,63 @@
 #!/bin/bash
-#Minecraft control script for use wiht minecraft.service
-FIFO_NAME="minecraftctl"
-#initial setup
-exec {stdout}>&1
-exec {shmlog}>/dev/shm/"minecraft@$1".log
-exec {stderr}>&2
-exec {minecraft_comm}<>"${FIFO_NAME}"
+# startattachable, a script to start a process as a daemon and provide the opportunity to attach to the console of this program
+
+WHAT="$1"; shift
+TOKEN="$1"; shift
+
+FIFO_NAME="/dev/shm/$TOKEN.ctl"
+LOG_FILE="/dev/shm/$TOKEN.log"
+
+COMMAND=$1; shift
+
+# setup fifo
+mkfifo "${FIFO_NAME}" #TODO: set access rights to current user write only
+
+#initial setup file handles
+exec {daemonlogfile}>"$LOG_FILE"
+exec {daemon_comm}<>"${FIFO_NAME}"
 
 # prepare cleanup
 function cleanup {
-  echo "Cleaning up" >&${stdout}
-  exec {minecraft_comm}>&-
-  exec {stdout}>&-
-  exec {stderr}>&-
+  exec {daemon_comm}>&-
+  rm  "$LOGFILE" "$FIFO_NAME"
 }
+
+function start {
 (
-#disable SIGTERM for the java process:
-trap "" SIGTERM
-#start the server process
-java -Xmx1024M -Xms1024M -Xincgc -jar server.jar <&${minecraft_comm} >&${shmlog} 2>&${shmlog} &
+#disable SIGTERM and SIGINT for the daemon process:
+trap "" SIGTERM # avoid kills by systemctl
+trap "" SIGINT # avoid kills when the interactive console is aborted
 
-# Now get the PID of java, issue stop, wait for it synchronously within the signal handler. and clean up afterwards -- 
-SVRPID=$!
-trap "echo stop >${FIFO_NAME}; wait $SRVPID" SIGTERM
+#start the daemon process
+$COMMAND $@  <&${daemon_comm} >&${shmlog} 2>&${shmlog} &
+
+# Now get the PID of daemon, issue stop, wait for it synchronously within the signal handler. and clean up afterwards -- 
+PID=$!
+trap "echo stop >${FIFO_NAME}; wait $PID" SIGTERM #TODO: make stop command configurable
 #wait and clean up afterwards
-wait $SRVPID >&${stdout}
-cleanup >&${stdout}
-) & >&${stdout}
+wait $PID 
+cleanup
+) & 
+}
 
+function connect {
+tail -f "$LOG_FILE"
+#start the interactive shell emulation
+#TODO: issue tail-f background, if possible, to create some kind of a interative shell
+while read line; do
+  if [ -p "${FIFO_NAME}" ]; then
+    echo "$line"
+  else
+    echo "named pipe does not exist anymore, aborting server frontend" >&${stderr}
+    break
+  fi
+done >"${FIFO_NAME}"
+}
+
+# evaluate command
+
+case "$WHAT" in 
+  start)
+    start
+  connect)
+    connect
